# ==============================================================================
# MODULE: AUTOSTART
# RESPONSIBILITY: Background daemons, polkit, wallpaper, status bar, exec-once rules
# ==============================================================================
exec-once = ~/.config/ml4w/scripts/ml4w-autostart
exec-once = ~/.config/waybar/launch.sh
exec-once = swaync
exec-once = hypridle
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = nm-applet --indicator
exec-once = blueman-applet
