# ==============================================================================
# MODULE: ENVIRONMENT VARIABLES
# RESPONSIBILITY: Environment variables, cursor sizes, toolkit backends, variables
# ==============================================================================
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,breeze_cursors
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = GDK_SCALE,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_CONFIG_HOME,/home/farrukh/.config
env = _JAVA_AWT_WM_NONREPARENTING,1
$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun
$clipboard = cliphist list | rofi -dmenu -p "Clipboard" | cliphist decode | wl-copy
